server:
  port: 18080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  jpa:
    show-sql: true
  hibernate:
    ddl-auto: none
  flyway:
    baseline-on-migrate: true
    baseline-version: 0

  datasource:
    url: jdbc:postgresql://localhost:5432/fc-gift
    username: postgres
    password: postgres
    flyway:
      user: postgres
      password: postgres
      schemas: fc-gift
      url: jdbc:postgresql://localhost:5432/fc-gift
      enabled: false

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: fc-msa
      max-poll-interval-ms-config: 6000
      enable-auto-commit: false

logging:
  config: classpath:logback-local.xml

example.order:
  base-url: http://localhost:8000/