### 선물하기 등록
POST http://localhost:18080/api/v1/gifts/register
Content-Type: application/json

{
  "buyerUserId": "6",
  "payMethod": "CARD",
  "pushType": "KAKAO",
  "giftReceiverName": "정가지",
  "giftReceiverPhone": "01000001111",
  "giftMessage": "축하한다 가지야~",
  "orderItemList": [
    {
      "orderCount": 2,
      "itemToken": "item_yuAzfZSNySTHIZRwRYxe",
      "itemName": "원피스",
      "itemPrice": "50000",
      "orderItemOptionGroupList": [
        {
          "ordering": 1,
          "itemOptionGroupName": "사이즈",
          "orderItemOptionList": [
            {
              "ordering": 1,
              "itemOptionName": "MEDIUM",
              "itemOptionPrice": 0
            }
          ]
        },
        {
          "ordering": 2,
          "itemOptionGroupName": "컬러",
          "orderItemOptionList": [
            {
              "ordering": 1,
              "itemOptionName": "RED",
              "itemOptionPrice": 0
            }
          ]
        }
      ]
    },
    {
      "orderCount": 1,
      "itemToken": "item_VxQylTtlXEPvewrUhkpr",
      "itemName": "목걸이",
      "itemPrice": "70000",
      "orderItemOptionGroupList": [
        {
          "ordering": 1,
          "itemOptionGroupName": "종류",
          "orderItemOptionList": [
            {
              "ordering": 1,
              "itemOptionName": "GOLD",
              "itemOptionPrice": 10000
            }
          ]
        }
      ]
    }
  ]
}

### 선물하기 결제중 상태로 변경
POST http://localhost:18080/api/v1/gifts/gt_OzJZCQheAJYVxXQWkriB/payment-processing
Content-Type: application/json

### 선물하기 수락 상태로 변경
POST http://localhost:18080/api/v1/gifts/gt_OzJZCQheAJYVxXQWkriB/accept-gift
Content-Type: application/json

{
  "receiverName": "정가지",
  "receiverPhone": "01000001111",
  "receiverZipcode": "123123",
  "receiverAddress1": "서울시 송파구",
  "receiverAddress2": "가지의 집",
  "etcMessage": "감사합니다!"
}

### 선물하기 조회
GET http://localhost:18080/api/v1/gifts/gt_OzJZCQheAJYVxXQWkriB
Content-Type: application/json